config/routes.rb
TrDemo::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  match '/registered_users', controller: 'home', action: 'registered_users'
  match '/banners', controller: 'home', action: 'banners'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :provider, :uid

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @refs = generate_links
  end

  def registered_users
    @users = User.all
  end

  def banners

  end

private
  def generate_links
    refs = []
    Dir[Rails.root.join("public/univer_pub/*")].each do |file|
      name = file.split('/').last.split('.').first.humanize
      path = file.split('public').last
      hashik = {:name => name, :path => path}
      refs << hashik
    end
    refs.sort_by { |k| k[:name] }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/banners.html.haml
:css
  #carousel {
  width: 450px;
  }
#carousel.carousel
  .carousel-inner
    .item.active
      %img{:alt => "Some Alt Text", :src => "/banners/01.jpg"}
      .carousel-caption
        Some caption
    .item
      %img{:alt => "Some Alt Text", :src => "/banners/02.jpg"}
      .carousel-caption
        Some caption
    .item
      %img{:alt => "Some Alt Text", :src => "/banners/03.jpg"}
      .carousel-caption
        Some caption
  %a.carousel-control.left{"data-slide" => "prev", :href => "#carousel"} &lsaquo;
  %a.carousel-control.right{"data-slide" => "next", :href => "#carousel"} &rsaquo;

app/views/home/index.html.haml
:css
  #carousel {
  width: 450px;
  }
  .carousel-caption {
  color:rgb(255,255,255);
  text-align:center;
  }

.row-fluid
  .span6
    %h3 Home
    - @refs.each do |ref|
      %p
        = ref[:name]
        = link_to 'Download', ref[:path], :target => '_blank'
  
  .span6
    #carousel.carousel
      .carousel-inner
        .item.active
          = link_to image_tag("/images/01.jpg"), "http://travel.com"
          / %img{:alt => "Some Alt Text", :src => "/images/01.jpg"}
          .carousel-caption
            Travel with us
        .item
          = link_to image_tag("/images/02.jpg"), "http://travel.com"
          / %img{:alt => "Some Alt Text", :src => "/images/02.jpg"}
          .carousel-caption
            Cheapest tickets
        .item
          = link_to image_tag("/images/03.jpg"), "http://travel.com"
          / %img{:alt => "Some Alt Text", :src => "/images/03.jpg"}
          .carousel-caption
            Hot tours
      %a.carousel-control.left{"data-slide" => "prev", :href => "#carousel"} &lsaquo;
      %a.carousel-control.right{"data-slide" => "next", :href => "#carousel"} &rsaquo;

app/views/home/registered_users.html.haml
- unless @users.empty?
  - @users.each do |user|
    %p
      User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Danci Ivan, Tr-1 Demo", root_path, :class => 'brand'
- unless user_signed_in?
  = link_to image_tag("/images/facebook-icon.png", :style => 'vertical-align: middle; width: 22px; height: 22px; margin-top:12px'), user_omniauth_authorize_path(:facebook)

%ul.nav
  %li
    = link_to 'Home', root_path
  - if user_signed_in?
    %li
      = link_to 'List users', registered_users_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
:css
  .bottombar {
    position: fixed;
    bottom: 15px;
    right: 15%;
    left: 15%;
  }
  .centertext{
    text-align:center;
  }
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Tr Demo"
      %meta{:content => content_for?(:description) ? yield(:description) : "Tr Demo", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer.bottombar.content.centertext
            = link_to image_tag("/images/rent.jpg", :style => 'vertical-align: middle;'), "http://rent-a-car.com"
      / ! end of .container
    / ! end of #main

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}